import fs from 'node:fs/promises';
import {Workbook,SpreadsheetFile} from '@oai/artifact-tool';
const root=process.argv[2];const d=JSON.parse(await fs.readFile(root+'/workbook_data.json','utf8'));const w=Workbook.create();
const cols=Object.keys(d.panel[0]);
for(const [name,rows,fields] of [['Canonical',d.panel,cols],['QA',d.qa,['check','result','evidence']]]){
 const s=w.worksheets.add(name);s.showGridLines=false;const mat=[fields,...rows.map(r=>fields.map(k=>r[k]??''))];s.getRangeByIndexes(0,0,mat.length,fields.length).values=mat;s.getRangeByIndexes(0,0,mat.length,fields.length).format.font={name:'Arial',size:10};s.getRangeByIndexes(0,0,mat.length,fields.length).format.columnWidth=22;
 s.getRangeByIndexes(0,0,1,fields.length).format={fill:'#253B53',font:{bold:true,color:'#FFFFFF'},rowHeight:35,wrapText:true};s.freezePanes.freezeRows(1);
 if(name==='Canonical'){s.getRange('B2:B1201').setNumberFormat('00');s.getRange('D2:D1201').setNumberFormat('0.000000');s.getRange('E2:F1201').setNumberFormat('#,##0');s.getRange('J:K').format.columnWidth=70;}else{s.getRange('A:A').format.columnWidth=36;s.getRange('C:C').format.columnWidth=55;}
 const preview=await w.render({sheetName:name,range:name==='Canonical'?'A1:F10':'A1:C12',scale:1.5,format:'png'});await fs.writeFile(root+'/'+name+'_preview.png',new Uint8Array(await preview.arrayBuffer()));
}
const s=w.worksheets.add('Method');s.showGridLines=false;const notes=[['Item','Definition'],['S6 unit','NAICS 813410 employer establishments per 1,000 July 1 residents'],['Derivation','Observed CBP establishments / official population * 1,000'],['Coverage','50 states; 2000–2023; DC and territories excluded'],['Observation status','All 1,200 rows DIRECT; model estimated rows 0'],['Population','2000–2009 intercensal; 2010–2019 vintage2020; 2020–2023 vintage2023'],['NAICS','1997 / 2002 / 2007 / 2012 / 2017. Core813410 definition unchanged'],['Limitation','Employer locations only; no nonemployer groups, memberships or utilization'],['Uncertainty','Administrative density; survey SE and CI not applicable'],['Risk flags','Population benchmark boundaries2010/2020; large countchanges retained'],['Count verification','All1,200 inherited counts match official rawZIP and archivedAPI']];s.getRange('A1:B11').values=notes;s.getRange('A1:B11').format.font={name:'Arial',size:10};s.getRange('A:A').format.columnWidth=25;s.getRange('B:B').format.columnWidth=110;s.getRange('A1:B11').format.rowHeight=28;s.getRange('A1:B1').format={fill:'#253B53',font:{bold:true,color:'#FFFFFF'}};
w.recalculate();console.log((await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#NUM!',options:{useRegex:true,maxResults:20}})).ndjson);const preview=await w.render({sheetName:'Method',range:'A1:B11',scale:1,format:'png'});await fs.writeFile(root+'/Method_preview.png',new Uint8Array(await preview.arrayBuffer()));await(await SpreadsheetFile.exportXlsx(w)).save(root+'/final_package/S6_FINAL_2000_2023.xlsx');
